#pragma once

#include "GPCS4Common.h"

typedef int32_t SceSystemParamLang;

// Language
#define SCE_SYSTEM_PARAM_LANG_JAPANESE (0)

#define SCE_SYSTEM_PARAM_LANG_ENGLISH_US (1)

#define SCE_SYSTEM_PARAM_LANG_FRENCH (2)

#define SCE_SYSTEM_PARAM_LANG_SPANISH (3)

#define SCE_SYSTEM_PARAM_LANG_GERMAN (4)

#define SCE_SYSTEM_PARAM_LANG_ITALIAN (5)

#define SCE_SYSTEM_PARAM_LANG_DUTCH (6)

#define SCE_SYSTEM_PARAM_LANG_PORTUGUESE_PT (7)

#define SCE_SYSTEM_PARAM_LANG_RUSSIAN (8)

#define SCE_SYSTEM_PARAM_LANG_KOREAN (9)

#define SCE_SYSTEM_PARAM_LANG_CHINESE_T (10)

#define SCE_SYSTEM_PARAM_LANG_CHINESE_S (11)

#define SCE_SYSTEM_PARAM_LANG_FINNISH (12)

#define SCE_SYSTEM_PARAM_LANG_SWEDISH (13)

#define SCE_SYSTEM_PARAM_LANG_DANISH (14)

#define SCE_SYSTEM_PARAM_LANG_NORWEGIAN (15)

#define SCE_SYSTEM_PARAM_LANG_POLISH (16)

#define SCE_SYSTEM_PARAM_LANG_PORTUGUESE_BR (17)

#define SCE_SYSTEM_PARAM_LANG_ENGLISH_GB (18)

#define SCE_SYSTEM_PARAM_LANG_TURKISH (19)

#define SCE_SYSTEM_PARAM_LANG_SPANISH_LA (20)

#define SCE_SYSTEM_PARAM_LANG_ARABIC (21)

#define SCE_SYSTEM_PARAM_LANG_FRENCH_CA (22)

// Date
#define SCE_SYSTEM_PARAM_DATE_FORMAT_YYYYMMDD (0)

#define SCE_SYSTEM_PARAM_DATE_FORMAT_DDMMYYYY (1)

#define SCE_SYSTEM_PARAM_DATE_FORMAT_MMDDYYYY (2)

// Time
#define SCE_SYSTEM_PARAM_TIME_FORMAT_12HOUR (0)

#define SCE_SYSTEM_PARAM_TIME_FORMAT_24HOUR (1)

// 
#define SCE_SYSTEM_SERVICE_MAX_SYSTEM_NAME_LENGTH (65)

//
#define SCE_SYSTEM_PARAM_GAME_PARENTAL_OFF (0)

#define SCE_SYSTEM_PARAM_GAME_PARENTAL_LEVEL01 (1)

#define SCE_SYSTEM_PARAM_GAME_PARENTAL_LEVEL02 (2)

#define SCE_SYSTEM_PARAM_GAME_PARENTAL_LEVEL03 (3)

#define SCE_SYSTEM_PARAM_GAME_PARENTAL_LEVEL04 (4)

#define SCE_SYSTEM_PARAM_GAME_PARENTAL_LEVEL05 (5)

#define SCE_SYSTEM_PARAM_GAME_PARENTAL_LEVEL06 (6)

#define SCE_SYSTEM_PARAM_GAME_PARENTAL_LEVEL07 (7)

#define SCE_SYSTEM_PARAM_GAME_PARENTAL_LEVEL08 (8)

#define SCE_SYSTEM_PARAM_GAME_PARENTAL_LEVEL09 (9)

#define SCE_SYSTEM_PARAM_GAME_PARENTAL_LEVEL10 (10)

#define SCE_SYSTEM_PARAM_GAME_PARENTAL_LEVEL11 (11)

//
typedef int32_t SceSystemParamEnterButtonAssign;

#define SCE_SYSTEM_PARAM_ENTER_BUTTON_ASSIGN_CIRCLE (0)

#define SCE_SYSTEM_PARAM_ENTER_BUTTON_ASSIGN_CROSS (1)
